[package]
name = "everscale-vm"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["proc"]

[[bench]]
name = "ever_wallet"
harness = false

[[bench]]
name = "jetton"
harness = false

[dependencies]
ahash = "0.8"
anyhow = "1.0"
bitflags = "2.4"
blake2 = "0.10.6"
bumpalo = "3.14"
castaway = "0.2.3"
dyn-clone = "1.0"
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
sha2 = "0.10.8"
thiserror = "1.0"
tracing = { version = "0.1", optional = true }

everscale-types = { version = "0.1.2", default-features = false, features = ["sync", "models"] }

everscale-vm-proc = { path = "./proc" }
everscale-crypto = "0.2.1"

[dev-dependencies]
criterion = "0.5"
hex = "0.4.3"
tracing = "0.1"
tracing-test = "0.2"

everscale-types = { version = "0.1.2", default-features = false, features = [
    "sync",
    "models",
    "base64",
] }
everscale-asm-macros = { git = "https://github.com/broxus/everscale-asm.git", rev = "1d02b25aa5582eb0ec02663c2192a54aa57d832e" }

[patch.crates-io]
everscale-types = { git = "https://github.com/broxus/everscale-types.git", rev = "16b1bb9c275137c2bd4e5a493a56a4c15309dab0" }
