[package]
name = "everscale-vm"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["proc"]

[dependencies]
ahash = "0.8"
anyhow = "1.0"
bitflags = "2.4"
blake2 = "0.10.6"
bumpalo = "3.14"
dyn-clone = "1.0"
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
sha2 = "0.10.8"
thiserror = "1.0"
tracing = { version = "0.1", optional = true }

everscale-types = { git = "https://github.com/broxus/everscale-types.git", default-features = false, features = [
    "sync",
    "models",
] }

everscale-vm-proc = { path = "./proc" }
everscale-crypto = "0.2.1"

[dev-dependencies]
tracing = "0.1"
tracing-test = "0.2"
hex = "0.4.3"

everscale-types = { git = "https://github.com/broxus/everscale-types.git", default-features = false, features = [
    "sync",
    "models",
    "base64",
] }
everscale-asm-macros = { git = "https://github.com/broxus/everscale-asm.git", rev = "3e7099f3c8352ef4c0c82f6b760fd7dff22bbd64" }

[patch."https://github.com/broxus/everscale-types.git"]
everscale-types = { git = "https://www.github.com/broxus/everscale-types.git", rev = "d9a691d2ed98fac5212c7837f40edb5a5ed67e7c" }
