[package]
name = "everscale-vm"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["proc"]

[dependencies]
ahash = "0.8"
anyhow = "1.0"
bitflags = "2.4"
bumpalo = "3.14"
dyn-clone = "1.0"
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
thiserror = "1.0"
tracing = { version = "0.1", optional = true }

everscale-types = { version = "0.1.0-rc.7", default-features = false, features = [
    "sync",
    "models",
] }

everscale-vm-proc = { path = "./proc" }

[dev-dependencies]
everscale-types = { version = "0.1.0-rc.7", default-features = false, features = [
    "sync",
    "models",
    "base64",
] }
#everscale-asm-macros = "0.0.1"
everscale-asm-macros = { git = "https://github.com/broxus/everscale-asm.git" }
tracing = "0.1"
tracing-test = "0.2"
